import styles from '../styles/globals.css'
import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import { Aside } from './componenets/Aside';
import { TiPlusOutline } from 'react-icons/ti';
import { Card } from './componenets/Card.js'
import { Cardinfos } from './componenets/Cardinfos';
import { Maps } from './componenets/Maps';


function MyApp({ Component, pageProps }) {

  const [tabs, settabs] = useState([])

  function createtab(id) {
    const index = arr.findIndex(object => {
      return object.id === id;
    });
    settabs(tabs => [...tabs, arr[index]])
  }

  const [cards, setcards] = useState([
  ])

  function cardcreator() {
    let newcard = {
      id: String(Math.random()),
      name: 'mage',
      img: 'https://static.wikia.nocookie.net/lawler-rpg/images/2/2c/Dissidia_black_mage_of_light_by_isaiahjordan-d5hz8q6.png',
    }
    setcards(cards => [newcard, ...cards])
  }


  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Bakbak+One&display=swap" rel="stylesheet" />
      </Head>
      <Aside />
      <Component {...pageProps} />

      <div className="right" id='right'>
        {
          tabs.map(function (element) {
            return <Cardinfos key={Math.random()}
              infos={element} />
          })
        }
      </div>

      <div className="creator" onClick={cardcreator} >
        <TiPlusOutline />
      </div>
    </div>
  )
}

export default MyApp
