import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import { GrFormSearch } from 'react-icons/gr';
import { TiPlusOutline } from 'react-icons/ti';
import { Card } from './componenets/Card.js'
import { Maps } from './componenets/Maps.js'
import { Cardinfos } from './componenets/Cardinfos';

export default function Home() {

  const [arr, setarr] = useState([{
    id: String(Math.random()),
    name: 'mage',
    img: 'https://static.wikia.nocookie.net/lawler-rpg/images/2/2c/Dissidia_black_mage_of_light_by_isaiahjordan-d5hz8q6.png',
  },
  {
    id: String(Math.random()),
    name: 'crusader',
    img: 'https://static.wikia.nocookie.net/finalfantasy/images/c/c8/WotV_Agrias.png  ',
  },
  {
    id: String(Math.random()),
    name: 'ranger',
    img: 'https://i.pinimg.com/originals/02/54/64/0254645c2624a84aac9a18e92df27c82.png',
  },
  ])

  const [tabs, settabs] = useState([])

  const [active, setactive] = useState("Characters")

  function cardcreator() {
    let newcard = {
      id: String(Math.random()),
      name: 'mage',
      img: 'https://static.wikia.nocookie.net/lawler-rpg/images/2/2c/Dissidia_black_mage_of_light_by_isaiahjordan-d5hz8q6.png',
    }
    setarr(arr => [newcard, ...arr])
    console.log(arr)
  }

  function createtab(id) {
    const index = arr.findIndex(object => {
      return object.id === id;
    });
    settabs(tabs => [...tabs, arr[index]])
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Bakbak+One&display=swap" rel="stylesheet" />
      </Head>

      <aside className={styles.aside}>
        <div className={styles.logo}> <img src="https://www.rederpg.com.br/wp/wp-content/uploads/2020/05/DD-Logo.png" alt="" /></div>
        <fieldset>
          <input type="text" placeholder='Search Something' />
          <GrFormSearch className={styles.icon} />
        </fieldset>
        <nav>
          <a href="#" onClick={() => { setactive("Characters") }}>CHARACTERS</a>
          <a href="#" onClick={() => { setactive("Maps") }}>MAPS</a>
          <a href="#">GUILDS</a>
          <a href="#">HISTORIES</a>
          <a href="#">DICES</a>
        </nav>
      </aside>

      <main className={styles.main}>
        {active === "Characters" && <Characters />}
        {active === "Maps" && <Maps />}

      </main>

      <div className={styles.right} id='right'>
        {

          tabs.map(function (element) {
            return <Cardinfos key={Math.random()}
              infos={element} />
          })
        }
      </div>

      <div className={styles.creator} onClick={cardcreator}>
        <TiPlusOutline />
      </div>
    </div>
  )






  function Characters() {
    return (
      arr.map(function (elements) {
        return (<div key={Math.random()} onClick={() => { createtab(elements.id) }}> <Card data={elements} /></div>)
      })
    )
  }

}
