import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GrFormSearch } from 'react-icons/gr';
import { Card } from './componenets/Card.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Bakbak+One&display=swap" rel="stylesheet" />
      </Head>

      <aside className={styles.aside}>
        <div className={styles.logo}> <img src="https://event.wwtonline.co.uk/security/wp-content/uploads/sites/94/2021/06/WUK-logo-Teal-RGB.png" alt="" /></div>
        <fieldset>
          <input type="text" placeholder='Search Something' />
          <GrFormSearch className={styles.icon} />
        </fieldset>
        <nav>
          <a href="#">CHARACTERS</a>
          <a href="#">MAPS</a>
          <a href="#">GUILDS</a>
          <a href="#">HISTORIES</a>
          <a href="#">DICES</a>
        </nav>
      </aside>

      <main className={styles.main}>
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
      </main>

      <div className={styles.right}></div>


    </div>


  )
}
